# Generated by Django 3.1.2 on 2020-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='Nombre:')),
                ('lastname', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='Nombre:')),
                ('lastname', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
