# Generated by Django 3.1.2 on 2020-10-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polleria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80, verbose_name='Nombre:')),
                ('Price', models.CharField(max_length=20, verbose_name='Precio')),
                ('Brand', models.CharField(max_length=200, verbose_name='Marca')),
                ('Expiration_date', models.CharField(max_length=50, verbose_name='Fecha de caducidad')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
